# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62a6d10bc28a66d48a340316c52616a3ae4393c21ace3582ae4a4f12a71c3dc76885b5feb7ce640503e4722d4ad79d57c063677535b0eb3eee531752040e280b

test:
  secret_key_base: b57117a53abf061abc58b7fd70b3184bb5c231f2f899245658da82319bcdb2fbdf046b7cbf2dfed6f7994749667c0f46f869aef583826fd1032c366f1846c31c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
